// apps/mobileExpo/app/(auth)/newArea/index.tsx
import React, { useState, useEffect } from "react";
import { View, ScrollView, Alert, StyleSheet } from "react-native";
import { Button, Card, Title, Paragraph, useTheme } from "react-native-paper";
import { useRouter } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import StringInput from "@/components/inputs/StringInput";
import NumberInput from "@/components/inputs/NumberInput";
import BooleanInput from "@/components/inputs/BooleanInput";
import DateInput from "@/components/inputs/DateInput";
import TextInput from "@/components/inputs/TextInput";
import SelectInput from "@/components/inputs/SelectInput";

const API_URL = process.env.EXPO_PUBLIC_API_URL;

const NewAreaScreen = () => {
  const [currentStep, setCurrentStep] = useState(0);
  const [services, setServices] = useState([]);
  const [triggerApp, setTriggerApp] = useState(null);
  const [actionApp, setActionApp] = useState(null);
  const [selectedTrigger, setSelectedTrigger] = useState(null);
  const [selectedAction, setSelectedAction] = useState(null);
  const [automationName, setAutomationName] = useState("");
  const [actionDetails, setActionDetails] = useState({ type: "", params: {} });
  const [reactionDetails, setReactionDetails] = useState({
    type: "",
    params: {},
  });
  const [dynamicVariables, setDynamicVariables] = useState([]);
  const theme = useTheme();
  const router = useRouter();

  const steps = [
    "Choose Trigger App",
    "Select Trigger",
    "Choose Action App",
    "Select Action",
    "Set up Details",
    "Test & Review",
  ];

  useEffect(() => {
    fetchServices();
  }, []);

  const fetchServices = async () => {
    try {
      const response = await fetch(`${API_URL}/services`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        throw new Error("Failed to fetch services");
      }

      const data = await response.json();
      setServices(data);
    } catch (error) {
      console.error("Failed to fetch services:", error);
      Alert.alert("Error", "Failed to fetch services");
    }
  };

  const nextStep = () =>
    setCurrentStep((prev) => Math.min(prev + 1, steps.length - 1));
  const prevStep = () => setCurrentStep((prev) => Math.max(prev - 1, 0));

  const selectApp = (app, type) => {
    if (type === "trigger") {
      setTriggerApp(app);
    } else {
      setActionApp(app);
    }
    nextStep();
  };

  const selectTriggerOrAction = (item, type) => {
    if (type === "trigger") {
      setSelectedTrigger(item);
      setActionDetails({
        type: item.type,
        params: {},
      });
      item.params.forEach((param) => {
        setActionDetails((prev) => ({
          ...prev,
          params: { ...prev.params, [param.name]: "" },
        }));
      });
      setDynamicVariables(item.variables || []);
    } else {
      setSelectedAction(item);
      setReactionDetails({
        type: item.type,
        params: {},
      });
      item.params.forEach((param) => {
        setReactionDetails((prev) => ({
          ...prev,
          params: { ...prev.params, [param.name]: "" },
        }));
      });
    }
    nextStep();
  };

  const updateParamValue = (store, paramName, value) => {
    if (store === "action") {
      setActionDetails((prev) => ({
        ...prev,
        params: { ...prev.params, [paramName]: value },
      }));
    } else {
      setReactionDetails((prev) => ({
        ...prev,
        params: { ...prev.params, [paramName]: value },
      }));
    }
  };

  const validateInputs = () => {
    const errors = [];
    if (!automationName.trim()) {
      errors.push("Automation name is required");
    }
    if (selectedTrigger?.params) {
      selectedTrigger.params.forEach((param) => {
        if (param.required && !actionDetails.params[param.name]) {
          errors.push(`Trigger parameter "${param.name}" is required`);
        }
      });
    }
    if (selectedAction?.params) {
      selectedAction.params.forEach((param) => {
        if (param.required && !reactionDetails.params[param.name]) {
          errors.push(`Action parameter "${param.name}" is required`);
        }
      });
    }
    return errors;
  };

  const handleCreateArea = async () => {
    try {
      const validationErrors = validateInputs();
      if (validationErrors.length > 0) {
        Alert.alert("Validation Error", validationErrors.join("\n"), [
          { text: "OK" },
        ]);
        return;
      }
      const token = await AsyncStorage.getItem("userToken");
      if (!token) {
        Alert.alert("Error", "Not authorized");
        return;
      }

      const newArea = {
        name: automationName,
        action: { type: actionDetails.type, ...actionDetails.params },
        reaction: { type: reactionDetails.type, ...reactionDetails.params },
      };
      const response = await fetch(`${API_URL}/areas`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(newArea),
      });
      const data = await response.json();
      if (!response.ok) {
        throw new Error(
          data.message || "Failed to create automation" + data.message,
        );
      }
      Alert.alert("Success", "New AREA created successfully");
      router.back();
    } catch (error) {
      console.error("Error creating new area:", error);
      Alert.alert("Error", "Failed to create automation");
    }
  };

  const renderInput = (param, store) => {
    const value =
      store === "action"
        ? actionDetails.params[param.name]
        : reactionDetails.params[param.name];
    const updateValue = (name, newValue) =>
      updateParamValue(store, name, newValue);

    switch (param.type) {
      case "string":
        return (
          <StringInput
            key={`${store}-${param.name}`}
            param={param}
            value={value}
            updateParamValue={updateValue}
            required={param.required}
            dynamicVariables={dynamicVariables}
            isAction={store === "action"}
          />
        );
      case "number":
        return (
          <NumberInput
            key={`${store}-${param.name}`}
            param={param}
            value={value}
            updateParamValue={updateValue}
            required={param.required}
            dynamicVariables={dynamicVariables}
            isAction={store === "action"}
          />
        );
      case "date":
        return (
          <DateInput
            key={`${store}-${param.name}`}
            param={param}
            value={value}
            required={param.required}
            dynamicVariables={dynamicVariables}
            updateParamValue={updateValue}
          />
        );
      case "text":
        return (
          <TextInput
            key={`${store}-${param.name}`}
            param={param}
            value={value}
            updateParamValue={updateValue}
            required={param.required}
            dynamicVariables={dynamicVariables}
            isAction={store === "action"}
          />
        );
      case "enum":
        return (
          <SelectInput
            key={`${store}-${param.name}`}
            param={param}
            options={param.items}
            value={value}
            updateParamValue={updateValue}
            required={param.required}
            dynamicVariables={dynamicVariables}
            isAction={store === "action"}
          />
        );
      default:
        return (
          <StringInput
            key={`${store}-${param.name}`}
            param={param}
            value={value}
            updateParamValue={updateValue}
            required={param.required}
            dynamicVariables={dynamicVariables}
            isAction={store === "action"}
          />
        );
    }
  };

  const renderStepContent = () => {
    switch (currentStep) {
      case 0:
      case 2:
        return (
          <>
            <Title style={styles.stepTitle}>
              Choose {currentStep === 0 ? "a Trigger" : "an Action"} App
            </Title>
            {services
              .filter((app) =>
                currentStep === 0
                  ? app.actions.length > 0
                  : app.reactions.length > 0,
              )
              .map((app) => (
                <Card
                  key={app._id}
                  style={styles.appCard}
                  onPress={() =>
                    selectApp(app, currentStep === 0 ? "trigger" : "action")
                  }
                >
                  <Card.Title title={app.name} />
                </Card>
              ))}
          </>
        );
      case 1:
      case 3:
        const currentApp = currentStep === 1 ? triggerApp : actionApp;
        const items =
          currentStep === 1 ? currentApp.actions : currentApp.reactions;
        return (
          <>
            <Title style={styles.stepTitle}>
              Select {currentStep === 1 ? "Trigger" : "Action"}
            </Title>
            {items.map((item) => (
              <Button
                key={item.action_type}
                mode="outlined"
                style={styles.itemButton}
                onPress={() =>
                  selectTriggerOrAction(
                    item,
                    currentStep === 1 ? "trigger" : "action",
                  )
                }
              >
                {item.name}
              </Button>
            ))}
          </>
        );
      case 4:
        return (
          <>
            <Title style={styles.stepTitle}>Set up Details</Title>
            <StringInput
              key="automation-name"
              param={{
                name: "Automation Name",
                details: "Enter a name for your automation",
                required: true,
              }}
              value={automationName}
              updateParamValue={(_, value) => setAutomationName(value)}
              required={true}
              dynamicVariables={[]}
              isAction={true}
            />
            {selectedTrigger && (
              <>
                <Title style={styles.subtitle}>Trigger Details</Title>
                {selectedTrigger.params.map((param) =>
                  renderInput(param, "action"),
                )}
              </>
            )}
            {selectedAction && (
              <>
                <Title style={styles.subtitle}>Action Details</Title>
                {selectedAction.params.map((param) =>
                  renderInput(param, "reaction"),
                )}
              </>
            )}
          </>
        );
      case 5:
        return (
          <>
            <Title style={styles.stepTitle}>Test & Review</Title>
            <Card style={styles.summaryCard}>
              <Card.Content>
                <Paragraph>Name: {automationName}</Paragraph>
                <Paragraph>Trigger App: {triggerApp?.name}</Paragraph>
                <Paragraph>Trigger: {selectedTrigger?.name}</Paragraph>
                <Paragraph>Action App: {actionApp?.name}</Paragraph>
                <Paragraph>Action: {selectedAction?.name}</Paragraph>
              </Card.Content>
            </Card>
            <Button
              mode="contained"
              onPress={handleCreateArea}
              style={styles.button}
            >
              Activate Automation
            </Button>
          </>
        );
      default:
        return null;
    }
  };

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: theme.colors.background }]}
    >
      <Card style={styles.card}>
        <Card.Title
          title={`Step ${currentStep + 1} of ${steps.length}`}
          subtitle={steps[currentStep]}
        />
        <Card.Content>{renderStepContent()}</Card.Content>
      </Card>
      <View style={styles.navigationButtons}>
        <Button mode="outlined" onPress={prevStep} disabled={currentStep === 0}>
          Back
        </Button>
        {currentStep < steps.length - 1 && (
          <Button mode="contained" onPress={nextStep}>
            Next
          </Button>
        )}
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  card: {
    margin: 16,
    elevation: 4,
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 16,
    marginBottom: 8,
  },
  input: {
    marginBottom: 12,
  },
  button: {
    marginTop: 24,
  },
  appCard: {
    marginBottom: 12,
  },
  itemButton: {
    marginBottom: 8,
  },
  summaryCard: {
    marginBottom: 16,
  },
  navigationButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginBottom: 16,
  },
});

export default NewAreaScreen;

// apps/frontend/src/routes/dashboard/new-area/+page.svelte
<script lang="ts">
	import { writable, type Writable } from 'svelte/store';
	import { enhance } from '$app/forms';
	import { goto } from '$app/navigation';
	import type { PageData } from './$types';
	import { fade, fly } from 'svelte/transition';
	import Icon from '@iconify/svelte';
	import ProgressBar from '$lib/components/new-area/ProgressBar.svelte';
	import MobileIndicator from '$lib/components/new-area/MobileIndicator.svelte';
	import AppCard from '$lib/components/new-area/AppCard.svelte';
	import AutomationSummary from '$lib/components/new-area/AutomationSummary.svelte';
	import TriggerBtn from '$lib/components/new-area/TriggerBtn.svelte';
	import StringInput from "$lib/components/new-area/Inputs/StringInput.svelte";
	import NumberInput from "$lib/components/new-area/Inputs/NumberInput.svelte";
	import BooleanInput from "$lib/components/new-area/Inputs/BooleanInput.svelte";
	import DateInput from "$lib/components/new-area/Inputs/DateInput.svelte";
	import Select from "$lib/components/new-area/Inputs/Select.svelte";
	import TextInput from "$lib/components/new-area/Inputs/TextInput.svelte";
	import type { App } from '$lib/types/App';
	import type { Action } from '$lib/types/Action';
	import type { ActionDetails } from '$lib/types/ActionDetails';
	import Success from "$lib/components/new-area/Success.svelte";
	import { setError } from "$lib/store/errorMessage";
	import AvailableVariable from "$lib/components/new-area/AvailableVariable.svelte";

	export let data: PageData;
	let apps: Writable<App[]> = writable([]);
	$: {
		if (data.services) {
			apps.set(data.services);
		}
	}
	const steps = [
		'Choose Trigger App',
		'Select Trigger',
		'Choose Action App',
		'Select Action',
		'Set up Details',
		'Test & Review'
	];
	let currentStep: Writable<number> = writable(0);
	let triggerApp: Writable<App | null> = writable(null);
	let selectedTrigger: Writable<Action | null> = writable(null);
	let actionApp: Writable<App | null> = writable(null);
	let selectedAction: Writable<Action | null> = writable(null);
	let automationName: Writable<string> = writable('');
	let actionDetails: Writable<ActionDetails> = writable({ type: '', params: {} });
	let reactionDetails: Writable<ActionDetails> = writable({ type: '', params: {} });
	let showSuccessAnimation = false;
	let dynamicVariables: Writable<{name: string, type: string, description: string, template: string}[]> = writable([]);

	function validateStep(): boolean {
		let errors: string[] = [];

		switch ($currentStep) {
			case 0:
				if (!$triggerApp) errors.push("Please select a trigger app");
				break;
			case 1:
				if (!$selectedTrigger) errors.push("Please select a trigger");
				break;
			case 2:
				if (!$actionApp) errors.push("Please select an action app");
				break;
			case 3:
				if (!$selectedAction) errors.push("Please select an action");
				break;
			case 4:
				if (!$automationName) errors.push("Automation name is required");
				if ($selectedTrigger) {
					$selectedTrigger.params.forEach(param => {
						if (param.required && !$actionDetails.params[param.name]) {
							errors.push(`Trigger parameter "${param.name}" is required`);
						}
					});
				}
				if ($selectedAction) {
					$selectedAction.params.forEach(param => {
						if (param.required && !$reactionDetails.params[param.name]) {
							errors.push(`Action parameter "${param.name}" is required`);
						}
					});
				}
				break;
		}

		if (errors.length > 0) {
			setError(errors.join('\n'));
			return false;
		}
		return true;
	}

	function nextStep(): void {
		if (validateStep()) {
			currentStep.update((n) => (n < steps.length - 1 ? n + 1 : n));
		}
	}

	function prevStep(): void {
		currentStep.update((n) => (n > 0 ? n - 1 : n));
	}

	function selectApp(app: App, type: 'trigger' | 'action'): void {
		if (type === 'trigger') {
			triggerApp.set(app);
		} else {
			actionApp.set(app);
		}
		nextStep();
	}

	function selectTriggerOrAction(item: Action, type: 'trigger' | 'action'): void {
		if (type === 'trigger') {
			selectedTrigger.set(item);
			actionDetails.set({ type: item.ActionType, params: {} });
			item.params.forEach(param => {
				actionDetails.update(details => {
					details.params[param.name] = '';
					return details;
				});
			});
			dynamicVariables.set(item.variables || []);
		} else {
			selectedAction.set(item);
			reactionDetails.set({ type: item.ActionType, params: {} });
			item.params.forEach(param => {
				reactionDetails.update(details => {
					details.params[param.name] = '';
					return details;
				});
			});
		}
		nextStep();
	}

	function updateParamValue(store: Writable<ActionDetails>, paramName: string, value: string | number | boolean): void {
		store.update(details => {
			details.params[paramName] = value;
			return details;
		});
	}

	function handleSubmit(event: Event) {
		if (!validateStep()) {
			event.preventDefault();
		}
	}

	function handleCreateAreaResult(result: { type: string; data?: { message: string } }): void {
		if (result.type === 'success') {
			showSuccessAnimation = true;
			setTimeout(() => {
				goto('/dashboard');
			}, 2000);
		} else {
			setError(`Failed to create automation: ${result.data?.message || 'Unknown error'}`);
		}
	}
</script>

<div class="container mx-auto px-4 py-8 flex">
	<div class="flex-1">
		<h1 class="h1 mb-8 text-center">Create New Automation</h1>

		<ProgressBar {steps} currentStep={$currentStep} />
		<MobileIndicator
				currentStep={$currentStep}
				totalSteps={steps.length}
				stepName={steps[$currentStep]}
		/>

		<div class="flex flex-col lg:flex-row gap-4 flex-grow">
			{#if $currentStep === 4 && $dynamicVariables.length > 0}
				<AvailableVariable {dynamicVariables} />
			{/if}
			<div class={ $currentStep >= 4 && $dynamicVariables.length > 0 ? 'w-full lg:w-3/4' : 'w-full' }>
				<div class="card variant-soft p-4 md:p-6 h-full overflow-y-auto">
					{#if showSuccessAnimation}
						<Success/>
					{:else if $currentStep === 0 || $currentStep === 2}
						<h2 class="h2 mb-4 text-center" in:fade>
							Choose {$currentStep === 0 ? 'a Trigger' : 'an Action'} App
						</h2>
						<div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
							{#each $apps.filter((app) => ($currentStep === 0 ? app.actions.length > 0 : app.reactions.length > 0)) as app (app._id)}
								<AppCard
										app={{...app, id: app._id, icon: 'mdi:application'}}
										onClick={() => selectApp(app, $currentStep === 0 ? 'trigger' : 'action')}
								/>
							{/each}
						</div>
					{:else if $currentStep === 1 || $currentStep === 3}
						<h2 class="h2 mb-4 text-center" in:fade>
							Select {$currentStep === 1 ? 'Trigger' : 'Action'}
						</h2>
						<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
							{#each ($currentStep === 1 ? $triggerApp?.actions : $actionApp?.reactions) || [] as item}
								<TriggerBtn
										item={item.name}
										type={$currentStep === 1 ? 'trigger' : 'action'}
										appName={$triggerApp?.name || $actionApp?.name}
										onClick={() => selectTriggerOrAction(item, $currentStep === 1 ? 'trigger' : 'action')}
								/>
							{/each}
						</div>
					{:else if $currentStep === 4}
						<h2 class="h2 mb-4 text-center">Set up Details</h2>
						<div class="mb-4">
							<label for="automation-name" class="label">Automation Name *</label>
							<div class="rounded-lg p-4">
								<input
										id="automation-name"
										type="text"
										class="input w-full"
										bind:value={$automationName}
										placeholder="Enter a name for your automation"
								/>
							</div>
						</div>
						{#if $selectedTrigger}
							<h3 class="h3 mb-2">Trigger Details</h3>
							{#each $selectedTrigger.params as param}
								<div class="mb-4">
									<label for={param.name} class="h3">{param.name}{param.required ? ' *' : ''}</label>
									{#if param.type === 'string'}
										<StringInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={true}
										/>
									{:else if param.type === 'number'}
										<NumberInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={true}
										/>
									{:else if param.type === 'boolean'}
										<BooleanInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={true}
										/>
									{:else if param.type === 'enum'}
										<Select
												options={param.items}
												value={$actionDetails.params[param.name]}
												on:change={(e) => updateParamValue(actionDetails, param.name, e.detail)}
												required={param.required}
												dynamicVariables={$dynamicVariables}
												isAction={true}
										/>
									{:else if param.type === 'date'}
										<DateInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												dynamicVariables={$dynamicVariables}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
										/>
									{:else if param.type === 'text'}
										<TextInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={true}
										/>
									{/if}
								</div>
							{/each}
						{/if}
						{#if $selectedAction}
							<h3 class="h3 mb-2">Action Details</h3>
							{#each $selectedAction.params as param}
								<div class="mb-4">
									<label for={param.name} class="h3">{param.name}{param.required ? ' *' : ''}</label>
									{#if param.type === 'string'}
										<StringInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={false}
										/>
									{:else if param.type === 'number'}
										<NumberInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={false}
										/>
									{:else if param.type === 'boolean'}
										<BooleanInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={true}
										/>
									{:else if param.type === 'enum'}
										<Select
												options={param.items}
												value={$actionDetails.params[param.name]}
												on:change={(e) => updateParamValue(actionDetails, param.name, e.detail)}
												required={param.required}
												dynamicVariables={$dynamicVariables}
												isAction={true}
										/>
									{:else if param.type === 'date'}
										<DateInput
												{param}
												required={param.required}
												value={$reactionDetails.params[param.name]}
												dynamicVariables={$dynamicVariables}
												updateParamValue={(name, value) => updateParamValue(reactionDetails, name, value)}
										/>
									{:else if param.type === 'text'}
										<TextInput
												{param}
												required={param.required}
												value={$actionDetails.params[param.name]}
												updateParamValue={(name, value) => updateParamValue(actionDetails, name, value)}
												dynamicVariables={$dynamicVariables}
												isAction={false}
										/>
									{/if}
								</div>
							{/each}
						{/if}
						<button class="btn variant-filled-primary w-full" on:click={nextStep}>Continue</button>
					{:else if $currentStep === 5}
						<h2 class="h2 mb-4 text-center">Test & Review</h2>
						<AutomationSummary
								name={$automationName}
								triggerApp={$triggerApp?.name}
								triggerAction={$selectedTrigger?.name}
								actionApp={$actionApp?.name}
								selectedAction={$selectedAction?.name}
						/>
						<form
								method="POST"
								action="?/createArea"
								use:enhance={() => {
								return async ({ result }) => {
									handleCreateAreaResult(result);
								};
							}}
								on:submit={handleSubmit}
						>
							<input type="hidden" name="actionDetails" value={JSON.stringify($actionDetails)} />
							<input type="hidden" name="reactionDetails" value={JSON.stringify($reactionDetails)} />
							<input type="hidden" name="areaName" value={$automationName} />
							<button type="submit" class="btn variant-filled-primary w-full">
								<Icon icon="mdi:flash" class="w-4 h-4 mr-2" />
								Activate Automation
							</button>
						</form>
					{/if}
				</div>
			</div>
		</div>
		<div class="flex justify-between mt-8">
			<button class="btn variant-soft" on:click={prevStep} disabled={$currentStep === 0}>
				<Icon icon="mdi:arrow-left" class="w-4 h-4 mr-2" />
				Back
			</button>
			<button class="btn variant-soft" on:click={nextStep} disabled={$currentStep >= steps.length - 1}>
				Next
				<Icon icon="mdi:arrow-right" class="w-4 h-4 ml-2" />
			</button>
		</div>
	</div>
</div>
